//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ats.Gop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public int PkId { get; set; }
        public byte TypeId { get; set; }
        public string Text { get; set; }
        public string Url { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual AnnouncementType AnnouncementType { get; set; }
    }
}
