//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ats.Gop
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnouncementDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnnouncementDefinition()
        {
            this.EmailAnnouncementDefinitions = new HashSet<EmailAnnouncementDefinition>();
        }
    
        public int PkId { get; set; }
        public string Url { get; set; }
        public byte TypeId { get; set; }
        public string RowCssSelector { get; set; }
        public string ClickCssSelector { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
    
        public virtual AnnouncementType AnnouncementType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailAnnouncementDefinition> EmailAnnouncementDefinitions { get; set; }
    }
}
