//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ats.Gop
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAnnouncementDefinition
    {
        public int PkId { get; set; }
        public int AnnouncementDefinitionId { get; set; }
        public int EmailId { get; set; }
    
        public virtual AnnouncementDefinition AnnouncementDefinition { get; set; }
        public virtual Email Email { get; set; }
    }
}
